apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-deployment
  labels:
    app: admin-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service-deployment
  template:
    metadata:
      labels:
        app: admin-service-deployment
    spec:
      containers:
      - name: admin-service-deployment
        image: giridharaguptha/ticket-booking-admin-service:1.0.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  selector:
    app: admin-service-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: ClusterIP
